In [1]:
import numpy as np
import pandas as pd
import os
import math
from IPython.display import Image, HTML

In [2]:
cwd = os.getcwd()
df = pd.read_csv(cwd + '/Data/C_Utah_Traffic.csv')
df.set_index(df.columns[0],inplace=True)

In [3]:
df.head()

long        lat  route  2022-01-01 00:00:00  \
Unnamed: 0                                                      
615        -112.249065  40.709543     80                804.0   
354        -111.939322  40.696619    171                533.0   
616        -111.914586  40.846103     15               2897.0   
634        -112.029834  40.603452     85                705.0   
711        -111.981560  40.711721    154                591.0   

            2022-01-01 01:00:00  2022-01-01 02:00:00  2022-01-01 03:00:00  \
Unnamed: 0                                                                  
615                       738.0                419.0                375.0   
354                       458.0                352.0                220.0   
616                      2604.0               1401.0                849.0   
634                       631.0                379.0                290.0   
711                       529.0                372.0                278.0   

            2022-01-01 04:00:00  2022-01-01 05:00:00  2022-01-01 06:00:00  \
Unnamed: 0                                                                  
615                       328.0                387.0                522.0   
354                       145.0                205.0                229.0   
616                       717.0                904.0               1308.0   
634                       197.0                204.0                268.0   
711                       264.0                323.0                384.0   

            ...  2022-01-31 14:00:00  2022-01-31 15:00:00  \
Unnamed: 0  ...                                             
615         ...               2776.0               3576.0   
354         ...               2187.0               2410.0   
616         ...               9290.0              11665.0   
634         ...               1915.0               2730.0   
711         ...               2862.0               2508.0   

            2022-01-31 16:00:00  2022-01-31 17:00:00  2022-01-31 18:00:00  \
Unnamed: 0                                                                  
615                      4389.0               4366.0               3064.0   
354                      2645.0               2470.0               1984.0   
616                     12776.0              13112.0               9317.0   
634                      3021.0               3307.0               2257.0   
711                       944.0               3440.0               2321.0   

            2022-01-31 19:00:00  2022-01-31 20:00:00  2022-01-31 21:00:00  \
Unnamed: 0                                                                  
615                      1664.0               1282.0               1014.0   
354                      1318.0                925.0                745.0   
616                      6013.0               4546.0               3524.0   
634                      1242.0                980.0                767.0   
711                      1498.0               1092.0               1027.0   

            2022-01-31 22:00:00  2022-01-31 23:00:00  
Unnamed: 0                                            
615                       675.0                517.0  
354                       565.0                498.0  
616                      2574.0               1634.0  
634                       515.0                335.0  
711                       391.0                575.0  

[5 rows x 747 columns]

In [4]:
l = len(df.index)
W = np.zeros((l,l))
W

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [5]:
#to calculate the weight matrix by adjacency
for i in range(l):
    for j in range(l):
        if i == j:
            continue
        elif df.iloc[i,2] == df.iloc[j,2]:
            W[i][j] = 100

In [6]:
W

array([[  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ..., 100.,   0., 100.],
       ...,
       [  0.,   0., 100., ...,   0.,   0., 100.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0., 100., ..., 100.,   0.,   0.]])

In [14]:
W1 = W.copy()

In [15]:
pnts=[]
   
def EUC_distance(point1, point2):
    distance = 0.0
    for i in range(len(point1)):
        distance += (point1[i] - point2[i])**2
    return math.sqrt(distance)

for i in range(len(df)):
    pnts.append([df.iloc[i,0],df.iloc[i,1]])


for i in range(len(pnts)):
    t = 0
    d_ij = 0
    pnts_adj = pnts.copy()
    pnts_adj.remove(pnts[i])
    
    for j in range(len(pnts_adj)):
        if i == j:
            continue
        d_ij = EUC_distance(pnts[i],pnts_adj[j])
        
        if d_ij < 1e-8:
            continue
        t = 1/(d_ij)
        W1[i][j] += t

            

In [16]:
W1

array([[  0.        ,   2.76792492,   4.10590471, ...,   1.20044697,
          1.19906447,   0.        ],
       [  3.22568176,   0.        ,   7.69858138, ...,   1.6207624 ,
          1.57411531,   0.        ],
       [  2.76792492,   6.59991493,   0.        , ..., 101.35646883,
          1.31234012, 100.        ],
       ...,
       [  1.24262954,   1.67450217, 101.38580497, ...,   0.        ,
         23.03256991, 100.        ],
       [  1.20044697,   1.6207624 ,   1.35646883, ...,  27.840304  ,
          0.        ,   0.        ],
       [  1.19906447,   1.57411531, 101.31234012, ..., 123.03256991,
         18.11507643,   0.        ]])

In [17]:
np.max(W1)

217.75976230119662

In [ ]:
for 

In [13]:
W1 = pd.DataFrame(W1,columns=df.index,index=None)
W1

Unnamed: 0         615        354         616        634         711  \
0             0.000000   2.767925    4.105905   3.738129    3.347473   
1             3.225682   0.000000    7.698581  22.293320   38.837134   
2             2.767925   6.599915    0.000000   6.660147    5.688950   
3             4.105905   7.698581    3.722603   0.000000    9.519474   
4             3.738129  22.293320    6.660147   8.435727    0.000000   
5             3.347473  38.837134    5.688950   9.519474   21.128316   
6             3.449945  10.737200    4.116657  18.522793  109.933624   
7             2.878435   7.240818   63.261906   3.947201    7.417915   
8             2.996637   6.928986   35.464051   3.951367    7.406210   
9             3.135809   8.213328   22.432887   4.363255    9.002482   
10          103.126267  14.478674   12.055874   5.313695   13.946561   
11            2.897724  26.953886  107.213121   6.114673   12.872486   
12            2.994883  31.172090    5.791889   7.536223   13.343578   
13            3.378610  65.118880    6.760310   7.943205   33.747409   
14            2.915685  15.278524    4.765420   8.307178    9.873871   
15            2.734593   9.082498  103.944257   7.826038    7.004924   
16            2.429667   5.101979  102.939043   5.907678    4.460912   
17            2.763278  15.371592    8.898336   5.139628   10.343618   
18            2.637280  12.418819    8.672356   4.785199    8.779764   
19            2.378795   8.227923    7.899981   4.033138    6.414452   
20          102.665343  14.527982    7.454981   5.165962    9.278255   
21          102.152044   6.408457    5.424079   3.706610    5.071817   
22            2.622057  13.284658    5.423270   5.813098    8.327563   
23            2.245383   7.218883    4.572718   4.368473    5.454059   
24            2.120738   5.829263    3.835124   4.097491    4.626949   
25            2.021327   4.828157    3.246203   3.877017    3.995132   
26            2.429667   5.101979    2.939043   5.907678  104.460912   
27            2.405235   4.334395  102.642297   5.540004    3.935783   
28            2.203857   3.705156  102.405820   4.515973    3.390801   
29            2.200351   3.501970    2.309339   4.389277    3.243490   
30            2.245407   3.216902    2.168213   4.268872    3.047121   
31            1.981798   3.237847  102.223419   3.691198    2.963152   
32            2.019472   3.534264    2.376014   3.897968    3.185597   
33            1.862440   2.972936  102.108136   3.300788    2.727996   
34            1.828631   2.928272    2.093255   3.207722    2.683447   
35            1.864410   2.955684    2.096734   3.298420    2.716423   
36            1.749730   2.760105  102.015946   2.976315    2.534659   
37            1.604364   2.459379  101.868794   2.585049    2.268878   
38            1.634135   2.581017    1.946404   2.679039    2.366394   
39            1.528571   2.294161  101.778687   2.393107    2.124765   
40            1.437129   2.150487    1.711831   2.188711    1.992279   
41            1.507208   2.227687  101.735746   2.334391    2.069476   
42            1.391612   1.969479  101.577413   2.059412    1.844722   
43            1.351654   1.938648    1.572345   1.987437    1.811072   
44            1.335975   1.894169    1.540355   1.949609    1.773466   
45            1.330825   1.862914    1.514388   1.931735    1.748466   
46            1.307964   1.806835  101.475223   1.879262    1.700081   
47            1.242630   1.674502  101.385805   1.741979    1.582902   
48            1.200447   1.620762    1.356469   1.667197    1.531709   
49            1.199064   1.574115  101.312340   1.647667    1.495138   

Unnamed: 0         637         627         628        624         501  ...  \
0             3.449945    2.878435    2.996637   3.135809    3.126267  ...   
1            10.737200    7.240818    6.928986   8.213328   14.478674  ...   
2             4.116657   63.261906   35.464051  22.432887   12.055874  ...   
3            18

In [227]:
W1.to_csv('Data/W_UT.csv', index=False)

### Further update W with distance based on semi-variance

$$\hat{\gamma}(h) = \frac{1}{2N(h)}\sum_{d_ij=h_\Delta/2}^{d_ij=h-\Delta/2}(z_i-z_j)^{2}$$
 
|parameters|description|
|:---:|:---:|
|h|a fixed distance or lag|
|$$\Delta$$|the width of a band whose centre is at h|
|$$d_ij$$|the distance between points i and j|
|N|the number of points in distance band h|

The semivariance is half of the
average of the sum of squared
differences between all points
in the distance band ℎ.


In [69]:
# define the function to calculate semi-variance
W1 = np.zeros((l,l))
W1


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [67]:
pnts = ([[1,2],[6,4],[5,7],[10,12]]
    
delta = 500
h = 1000

for i in range(len(pnts)):
    d_ij = 0
    gamma = 0
    N = 0
    
    pnts_adj = pnts.copy()
    pnts_adj.remove(pnts[i])
    
    for j in range(len(pnts_adj)): 
        d_ij = EUC_distance(pnts[i],pnts_adj[j])
        
        if d_ij >= h-2*delta and d_ij <= h+2*delta:
            N += 1
            gamma += (mean(df.iloc[i, 3:])-mean(df.iloc[j:3]))**2
            gamma = (1/2*N)*gamma
    
                     
def EUC_distance(point1, point2):
    distance = 0.0
    for i in range(len(point1)):
        distance += (point1[i] - point2[i])**2
    return math.sqrt(distance)
            
        
        
    
    
        
    

             
        
        